# Plain-English "what is this toolkit" one-liners. Casual tone, factual,
# grounded in the same source documentation used to score each toolkit.
# Separate from the Q3-specific evidence text -- this is "what is it", not
# "why does it match your priority".
DESCRIPTIONS = {
    "T01": "A set of practices from Microsoft to help teams spot risks early, before they've built anything.",
    "T02": "A UK government checklist for thinking through the ethics of a data project.",
    "T03": "A simple template for writing down where your data came from and what its limitations are.",
    "T04": "A quick team exercise (about an hour) to think through what could go wrong with something you're building.",
    "T05": "Like a nutrition label for an AI model, showing what it does and doesn't do well.",
    "T06": "A checklist data teams can run through to catch ethical issues as they build.",
    "T07": "A code library for measuring and reducing bias in your data or model. Built for people who can code.",
    "T08": "A visual, no-code tool for poking at a model to see how it behaves, without needing to write anything.",
    "T09": "A step-by-step guide for buying AI responsibly, aimed at procurement teams.",
    "T10": "A big-picture set of principles from an engineering body on what ethical AI should look like.",
    "T11": "A tool that checks a model for bias and produces a report, but doesn't fix anything itself.",
    "T12": "A structured way to assess how an AI system might affect the public before it's rolled out.",
    "T13": "A government risk toolkit that scores how risky an algorithm is and suggests ways to reduce that risk.",
    "T14": "A one-page worksheet of questions to help you think through the ethics of using some data.",
    "T15": "Official UK guidance on how to explain an AI decision to the person it affects.",
    "T16": "An industrial-strength checklist (from Rolls-Royce) for keeping AI systems safe and accountable over time.",
    "T17": "A self-assessment built specifically for startups and entrepreneurs, not big companies.",
    "T18": "A reflective exercise for thinking about fairness and inclusion in the AI field more broadly, rather than a specific system.",
    "T19": "A consulting-style diagnostic that scores how ready your organisation is across five areas.",
    "T20": "A toolkit of future scenarios to help you spot risks (like bias or misuse) before you build.",
    "T21": "A widely-used US framework covering the full picture: governing, mapping, measuring, and managing AI risk.",
    "T22": "An EU self-assessment checklist covering everything from fairness to human oversight.",
    "T23": "An international certifiable standard for running AI responsibly as an organisation, similar to ISO 27001 for security.",
    "T24": "The risk-management half of the ISO standard, focused specifically on identifying and handling AI risks.",
    "T25": "Microsoft's internal company-wide standard, including a template for assessing a system's impact before release.",
    "T26": "A commercial platform that helps companies track AI risk and compliance across their whole AI portfolio.",
    "T27": "Another commercial governance platform, similar to Credo AI, with a strong focus on testing models directly.",
    "T28": "Google's framework specifically for AI security, things like preventing data leaks or manipulated inputs.",
    "T29": "IBM's platform for documenting and monitoring AI models automatically as they run.",
    "T30": "A free UK regulator (ICO) spreadsheet for working through data protection risks in an AI project.",
    "T31": "An OECD framework for describing what kind of AI system you have, rather than judging it.",
    "T32": "A free, open-source testing toolkit from Singapore's government for checking a system against multiple principles.",
}
